name: Frontend CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Ajusta esto a la versión de Node.js que uses
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Test
      run: npm test
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: frontend-build
        path: build  # Ajusta esto a la carpeta de salida de tu build de Svelte

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: frontend-build
        path: build
    
    - name: Deploy to staging
      run: |
        echo "Deploying to staging environment"
        # Aquí irían los comandos para desplegar a tu entorno de staging
        # Por ejemplo, si usas GitHub Pages:
        # - name: Deploy to GitHub Pages
        #   uses: peaceiris/actions-gh-pages@v3
        #   with:
        #     github_token: ${{ secrets.GITHUB_TOKEN }}
        #     publish_dir: ./build
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}